# Generated by Django 5.2.9 on 2026-01-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0005_remove_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, through='platform_web.ProjectSkill', through_fields=('project', 'skill'), to='platform_web.skill'),
        ),
    ]
