# Generated by Django 5.2.9 on 2026-01-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0006_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
    ]
